config/routes.rb
NuvolaWebsite::Application.routes.draw do
  

  get "pages/home"
  get "pages/elearning"
  get "pages/about"
  get "pages/av"
  get "pages/cloud"
  get "pages/app"
  get "pages/web"
  get "pages/services"
  get "pages/contact"
  
  get "pages/coursedev"
  get "pages/vle"
  get "pages/consult"
  
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/services'  => 'pages#services'
  get '/home' => 'pages#home'
  get '/cloud' => 'pages#cloud'
  get '/app' => 'pages#app'
  get '/av' => 'pages#av'
  get '/elearning' => 'pages#elearning'
  get '/web'=> 'pages#web'
  get '/vle' => 'pages#vle'
  get '/consult' => 'pages#consult'
  get '/coursedev' => 'pages#coursedev'
  get'/ourwork' => 'pages#videoexamples'

root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
      @title = "Home"
  end

  def about
      @title = "About Us"
  end

  def services
      @title = "Services"
  end

  def contact
      @title = "Contact Us"
  end
# product and services pages
  
  def elearning
    @title = "e-Learning"
  end
  
  def av
    @title = "A/V Production"
  end
  
  def app
    @title = "App Development"
  end
  
  def cloud
    @title = "cloud Services"
  end
  
  def web
    @title = "Web Design"
  end

# elearning pages

  def coursedev
    @title = "Course Development"
  end
    
  def vle
    @title = "VLE"
  end
    
  def consult
    @title = "e-Learning Consultation" 
  end
    
    # A/V pages
    
    def videoexamples
        @title = "Our Work"
        end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
        
        # Return a title on a per-page basis.
        
        def title
            base_title = "Nuvola Networks"
            if @title.nil?
                base.title
                else
                "#{base_title} | #{@title}"
                
            end
        end
    end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>Powered by <%= link_to "Nuvola Networks", 'home' %>
    | Created by <%= link_to "Rick Barkley Design", "http://www.rickbarkleydesign.com" %>
  </small>
  <menu>
    <ul>
      <li><a href="http://www.twitter.com/nuvolanetworks" target="_blank">Twitter</a></li>
      <li><a href="http://www.facebook.com/nuvolanetworks" target="_blank">Facebook</a></li>
      <li><a href="#">News</a></li>
    </ul>
  </menu>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title> <%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>
	<header>
		<%= link_to image_tag("6_13_new_header.png", alt: "Nuvola Networks"), 'home' %>
    </header>  
		<nav class="navbar navbar-inverse">
			<div class "navbar-inner">
				<div class = "container">
            <ul class="nav pull-left">
              <li><%= link_to "Home",    'home' %></li>
              <li><%= link_to "About YOU",    'about' %></li>

			<ul class="nav">
			  <li class="dropdown">
			    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			      Products/Services
			      <b class="caret"></b>
			    </a>
			    <ul class="dropdown-menu">
				  <li><%= link_to "e-Learning", 'elearning' %></li>
				  <li><%= link_to "Video Production", 'av' %></li>
				  <li><%= link_to "Web Design/App Development", 'web' %></li>
				  <li><%= link_to "Nuvola Academy", 'app' %></li>
				  <%#<li><%= link_to "Cloud Services/Consulting", 'cloud' %></li>
              </ul>
			</li>
			  <li><%= link_to "Contact Us",    'contact' %></li>
            </ul>
          </nav>
        </div>
      </div>
    <div class="container">
      <%= yield %>
	<%= render 'layouts/footer' %>
	<subfooter>
		<div class="pagination-centered">
		<%= link_to image_tag("N_cloud_small.png", alt: "Nuvola Networks"), 'home' %>	
	</subfooter>
	</div>	
    </div>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
	  ga('send', 'pageview');

	</script>
  </body>
</html>

app/views/pages/about.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script>
<div class="center hero-unit">
  <h1>About YOU</h1>

 <br />
<br />
<p>
	<%= image_tag("migrating-to-the-cloud.png", :align => 'left') %>
	<strong>A lot of companies have an About “Us” page.  They talk about all the things they do, and it is up to you to decide if they can help meet your needs.<br /><br />
	At Nuvola we do things a little differently.  It is not about us, it is about YOU.</strong> 
	<br /><br />
	What do YOU need to succeed and how can technology help you.
	<br /><br />
	Are YOU an organization that needs to deliver compliance training to a large audience? We work with compliance regulators to make sure that YOUR training meets the requirements. We can develop curriculum, produce content, and host the Learning Management System. Do YOU look like Texas Charter School Association? Learn how Nuvola Networks served TCSA <a href="http://tcsa.nuvola-networks.com" target="_blank">Here</a>.
	<br /><br />
	Are you a small to medium size business that wants to take advantage of new technology to help promote growth, but not sure how?
	<br /><br /> 
	Are you a business that needs help building your brand, showcasing a new product, or promoting an event? Check out our Video Production Services <%= link_to "Here", av_path %> 
	<br /><br />
	Do you need a custom application developed for you business, but don't want to hire a full time developer?
	<br /><br />
	Are YOU a company that has developed a product that needs complex end-user training? Our script writers can make engaging and educational training courses for the most complex products. Do YOU look like Innography? Learn how Nuvola Networks served Innography <a href="http://innography.nuvola-networks.com" target="_blank">Here</a>.
	<br /><br />
	Are you looking for new and better ways to train your employees?
	<br /><br />
	We would love to hear more about you and what you need as it relates to IT, training, and taking advantage of technology to create competitive advantages.
	</p>
	<div class="pagination-centered">
	<%= link_to "Let us Know What you Need", 'contact', class: "btn btn-large btn-primary" %>
</div>
</div>

app/views/pages/app.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script>
<div class="center hero-unit">
<h1>Nuvola Academy</h1>

<p><a href="http://www.nuvola-academy.com">Nuvola Academy</a> is a revolutionary approach to education. The training to help you succeed <b>when you need it, and where you want it</b>. Build communities, see what's trending, and connect with like minded individuals who share a passion similar to your own.</p>
<br /><br />
<p>Whether you are an expert looking for ways to monetize your knowledge and teach others, a learner seeking new avenues to increase your knowledge, or an organization looking for better ways to train your employees or customers, find our more info <a href="http://www.nuvola-academy.com">here.</a></p>

</div>

app/views/pages/av.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script><div class="center hero-unit">
<h1>Production Services</h1>
<br />
<p>Whether you need help <strong>building your brand, showcasing a new product, promoting an event, or providing training</strong> Nuvola Networks Video Production capabilities can help take your business to the next level.  Read more about how we can help and check out a sample of our work</p>
<br /><br />
<p><h1>How We Can Help...</h1></p><br />
<videos>
<p><strong>Build Your Brand:</strong></p>
<center><iframe src="http://player.vimeo.com/video/72456984" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
<p><strong>Create a Commercial:</strong></p>
<center><iframe src="http://player.vimeo.com/video/72456983" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
<p><strong>Showcase a New Product:</strong></p> 
<center><iframe src="http://player.vimeo.com/video/72457205" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
 <p><strong>Promote An Event:</stong></p>
<center><iframe src="http://player.vimeo.com/video/72456986" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
 <p><strong>Create a Highlight Reel:</strong></p>
<center><iframe src="http://player.vimeo.com/video/72456985" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
<p><strong>Provide Training For A New Product:</strong></p> 
<center><iframe src="http://player.vimeo.com/video/72457574" width="500" height="375" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
<p><strong>Record Training for Additional Distribution</strong></p>
<center>
	<iframe src="//player.vimeo.com/video/92345838" width="500" height="375" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</center>
</videos>
</div>

app/views/pages/cloud.html.erb
<div class="center hero-unit">
<h1>Cloud Services</h1>
</div>

app/views/pages/consult.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script>
<div class="center hero-unit">
<h1>e-Learning | Consulting Services</h1><br />
<p><%= image_tag("migrating-to-the-cloud.png", :align => 'right') %></p>

<br /><p><strong>Are you thinking about taking your training online?</strong>  Are you unhappy with your current training environment?  Whether you are a traditional school or a for-profit business, Learning, Development, and Education, are in the midst of dramatic fluctuations as new technologies are coming to market.  What makes sense for your organization?  How do you build an effective online learning strategy, or is it even necessary?  Nuvola Networks has a team of experts ready to work with you to help you wade through the myriad of possibilities, and design a solution that meets your needs in the most efficient way.  Sign up for a free one hour consultation!</p>
<br />
<h2><%= link_to "Back", 'elearning' %></h2>
</div>

app/views/pages/contact.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script>
<div class="center hero-unit">
  <h1>Contact Us</h1>

 <br />
<br />
<p>
	For any additional info or a free consultation please contact us at <%= mail_to "info@nuvola-networks.com" %> or call us at 512-698-8913.
	
	Thanks!
	</p>
</div>

app/views/pages/coursedev.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script>
<div class="center hero-unit">
<h1>e-Learning | Course Development</h1><br />
<p><%= image_tag("Course.png", :align => 'left') %></p>
<br /><p><strong>Course Development and Design are key components of any online learning management system.</strong>  Nuvola seeks to do more than just host training online, we seek to work with you to help design cutting edge courses that are effective modes of communication, and enable students to learn in new and powerful ways.</p> 
<br />
<h2><%= link_to "Back", 'elearning' %></h2>
</div>

app/views/pages/elearning.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script>
<div class="center hero-unit">
<h1>e-Learning</h1>

<p><b>Nuvola Networks</b> combines <b>Learning Management Systems</b> with <b>E-Commerce</b> to provide a new and powerful way to reach and educate your customers.  We offer this <b>“As A Service”</b> using a convenient "pay per click" model that allows you to distribute training content anytime, anywhere.</p>
<p>In addition we provide <b>content development, instructional design expertise, and production capabilities</B>.  Ask us how we can open up new revenue opportunities for you or your organization!</p> <br />
	
<p>For more information click on one of the pictures below, or take a look at our <b><%= link_to "e-Learning brochure", '/Nuvola Networks - VLE.pdf' %></b> for more info.</p>

<br />
	<%= link_to image_tag("lms_final.png"), 'vle' %>
	<%= link_to image_tag("cloud_final.png"), 'coursedev' %>
	<%= link_to image_tag("consult_final.png"), 'consult' %>
	
</div>

app/views/pages/home.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script>
<div class="center hero-unit">
  <h1>Welcome to Nuvola Networks</h1>

 <br />
<br />

<p>
		<%= link_to image_tag("Cloud-Computing.png", :align => 'left', :padding => '7px', alt: "Nuvola Networks") %>
	<strong>Like a bolt of lightning, emerging technologies are dramatically transforming the business landscape.</strong></p><p> At Nuvola we believe that businesses must quickly adapt and learn how to harness disruptive technology as soon as possible. Nuvola uses the Build-Measure-Learn methodology in all of our projects and employs a vast array of experts to help your business innovate and achieve more.  Whether it is through <strong><%= link_to "Custom Web/App Development", web_path %>, <%= link_to "Video Production", av_path %> or <%= link_to "e-Learning Design & Development", elearning_path %></strong> we can empower your company for success. View the About and Product pages to learn more about how we can help.
	</p>

	<div class="pagination-centered">
	 
	 <%= link_to "Ask About Our Free Consultation", 'contact', class: "btn btn-large btn-primary" %>
	</div>
  
</div>

app/views/pages/services.html.erb
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>

app/views/pages/videoexamples.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script>
<div class="center hero-unit">
<h1>How We Can Help</h1>
<videos>
<p><strong>Build Your Brand:</strong></p>
<center><iframe src="http://player.vimeo.com/video/72456984" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
<p><strong>Create a Commercial:</strong></p>
<center><iframe src="http://player.vimeo.com/video/72456983" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
<p><strong>Showcase a New Product:</strong></p> 
<center><iframe src="http://player.vimeo.com/video/72457205" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
 <p><strong>Promote An Event:</stong></p>
<center><iframe src="http://player.vimeo.com/video/72456986" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
 <p><strong>Create a Highlight Reel:</strong></p>
<center><iframe src="http://player.vimeo.com/video/72456985" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
<p><strong>Provide Training For A New Product:</strong></p> 
<center><iframe src="http://player.vimeo.com/video/72457574" width="500" height="375" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></center>
<p><strong>Record Training for Additional Distrobution</strong></p>
<center>
	<iframe src="//player.vimeo.com/video/92345838" width="500" height="375" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</center>
</videos>
</div>

app/views/pages/vle.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script>
<div class="center hero-unit">
<h1>e-Learning | Virtual Learning Enviroment</h1><br />
<p>
<%= image_tag("hightech.png", :align => 'left') %></p>
<br /><p><strong>Education is currently in the midst of a dramatic shift.</strong>  The traditional classroom based methodology is quickly giving way to new approaches which use cutting edge technology to deliver pointed and valuable education to the individuals and companies who need it.  Education that is <b>relevant</b>, and always <b>readily available</b> no matter where you are.  
	<br />	
	<p>Nuvola can design, implement, host, and manage a robust learning environment.   Whether you want us to design and deliver a standalone solution or want us to completely host and manage your learning environment we have a solution for you.  Ask us about our pay-for-use cost models.  Not only is Nuvola able to build custom VLE’s But we are seeking to transform the education industry through constant innovation.</p> </p>
<br />
<h2><%= link_to "Back", 'elearning' %></h2>
</div>

app/views/pages/web.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43996960-1', 'nuvola-networks.com');
  ga('send', 'pageview');

</script>
<div class="center hero-unit">
<h1>Web Design & App Development</h1>

<p>Whether you need a website built from scratch, need us to host/manage an existing site, or need us to build custom applications for your site or business, we are here to help.</p>

<p><b>Areas we specialize in:</b></p>

<div class="special span10">


			<center><p>Responsive Design | fluid architecture no matter what device you use</p></center><br />

			</div>
		<div class="-left-special span5">
			<ol>
			<p>Site Management and Hosting</p>
			<p>Graphic Design</p>
			<p>Mobile Development</p>
			<p>Various Programming Languages</p>
			<p>E Commerce Sites</p>
			<p>Search Engine Optimization (SEO)</p> 
			<p>Ruby on Rails</p>
			</ol>

	</div>
	<div class="right-special span5">
		<ol>
			<p>Content management systems</p>
				<p>Joomla</p>
				<p>WordPress</p>
				<p>Drupal</p>
				<p>Custom App Development</p>
				<p>Blogs</p>
				<p>Moodle</p>
			</ol>	
		</div>	
<div class="span10">
<center>	<p><b>Check out some of our work:</b></p> </center><br />
</div>
<div class="webdev span5">

<ol>
	<p>
	<a href="http://www.nuvola-academy.com">Nuvola Academy</a></p>
		<p><a href="http://www.nuvolio.com">Nuvolio</a></p>
	<p><a href="http://www.eamproject.org">East Africa Metamorphosis Project</a></p>
	</ol>
</div>	
<div class="appdev span5">
<ol>
	<p><a href="http://tcsa.nuvola-networks.com">TCSA e-Learning Portal</a></p>
	<p><a href="http://coxtraining.nuvola-networks.com">Cox Training Solutions | Technical Training</a></p>
	<p><a href="http://www.eplanbook.com">ePlanbook</a></p>

</ol>
<br />

</div>

<br />
<div class="end span10">
<p>In addition to web design and custom app development Nuvola Networks can also host and completely manage your site for you. <%= link_to "Contact us now", contact_path %> for a quote!</p> 
</div>
<br /><br />
<center><h3>Prices starting as low as $500 for a complete custom web site</h3></center>
</div>